// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOD0sSOprcH96AIdwhAYA6FbCSfjLWdOY',
    appId: '1:877890530634:web:a4f299a7b3fb3ca21025b3',
    messagingSenderId: '877890530634',
    projectId: 'worldcup2026-1',
    authDomain: 'worldcup2026-1.firebaseapp.com',
    storageBucket: 'worldcup2026-1.firebasestorage.app',
    measurementId: 'G-E9QNW9Q4QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9I2Huy4m26WCvt4TWbSmB7DLUTF-uE5o',
    appId: '1:877890530634:android:450d6e3599b898761025b3',
    messagingSenderId: '877890530634',
    projectId: 'worldcup2026-1',
    storageBucket: 'worldcup2026-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptSCeE120QA1udkBifTPshNsJ72Veq6M',
    appId: '1:877890530634:ios:dc443e73a9050df91025b3',
    messagingSenderId: '877890530634',
    projectId: 'worldcup2026-1',
    storageBucket: 'worldcup2026-1.firebasestorage.app',
    iosBundleId: 'com.adnan.kamran.worldcup2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBptSCeE120QA1udkBifTPshNsJ72Veq6M',
    appId: '1:877890530634:ios:dc443e73a9050df91025b3',
    messagingSenderId: '877890530634',
    projectId: 'worldcup2026-1',
    storageBucket: 'worldcup2026-1.firebasestorage.app',
    iosBundleId: 'com.adnan.kamran.worldcup2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOD0sSOprcH96AIdwhAYA6FbCSfjLWdOY',
    appId: '1:877890530634:web:097e97a1845e33b11025b3',
    messagingSenderId: '877890530634',
    projectId: 'worldcup2026-1',
    authDomain: 'worldcup2026-1.firebaseapp.com',
    storageBucket: 'worldcup2026-1.firebasestorage.app',
    measurementId: 'G-FLD825P6RB',
  );

}